### ISSUE TITLE
Create Button Component

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/projects#25]
<img width="238" alt="image" src="https://github.com/acm-ucr/projects/assets/36285610/92b71459-cd13-49a7-bc27-8f6670477acc">

- /components/Button.jsx
- need to account for different text, handlers and border colors

**Comment by yashkathe** [comment]
![Screenshot from 2024-01-29 20-30-21](https://github.com/acm-ucr/projects/assets/62693195/21accc27-b683-4a4f-a42a-a49812d3d4dc)
Created a custom button component which takes 4 arguments
1. buttonText = text to display in button
2. onClick = onClick handler
3.  textColor = (optional) gives white text color if no argument is passed
4.  borderColor - adds border color

The colors can be: 
1. blue
2. red
3. violet
4. purple:
5. white
6. orange
7. emerald
8. black
